### ISSUE TITLE
File gambar tidak ditemukan

### ISSUE THREAD

**Issue by jayaputra** [rsuregar/GundalaCMS#12]
![Screenshot at Mar 26 00-13-17](https://user-images.githubusercontent.com/33894932/77565627-18300880-6ef7-11ea-8b85-ec431cc60380.png)

Lokasi penempatan gambar berbeda dengan yg ada di alamat browser sehingga  gambar tidak muncul.
file apa yg harus saya edit?

makasih.

**Comment by rsuregar** [comment]
hmm... Coba di .env diedit APP_URL: http://localhost:8000. Kemudian, php artisan config:cache

**Comment by jayaputra** [comment]
Sip, sudah aman. Terima kasih.

**Comment by jayaputra** [comment]
Sekalian disini aja ya, ada isu dimana submenu tidak tampil

Berikut settingan menu saya di cms

![Screenshot at Mar 26 11-16-18](https://user-images.githubusercontent.com/33894932/77609877-c49fd800-6f53-11ea-8c11-1442774c5541.png)

Menu di halaman depan

![Screenshot at Mar 26 11-22-29](https://user-images.githubusercontent.com/33894932/77610022-22342480-6f54-11ea-939b-9b562ee8e8be.png)

Apakah settingan saya ada yg salah? mohon koreksinya. Makasih.

**Comment by rsuregar** [comment]
Untuk menu yang memiliki submenu. Harus pilih tipe menu sebagai submenu. Jadi tinggal edit aja menu putra, menjadi submenu. 
*Harusnya nanti saya ubah namanya biar ga ambigu.

**Comment by rsuregar** [comment]
> Sekalian disini aja ya, ada isu dimana submenu tidak tampil
> 
> Berikut settingan menu saya di cms
> 
> ![Screenshot at Mar 26 11-16-18](https://user-images.githubusercontent.com/33894932/77609877-c49fd800-6f53-11ea-8c11-1442774c5541.png)
> 
> Menu di halaman depan
> 
> ![Screenshot at Mar 26 11-22-29](https://user-images.githubusercontent.com/33894932/77610022-22342480-6f54-11ea-939b-9b562ee8e8be.png)
> 
> Apakah settingan saya ada yg salah? mohon koreksinya. Makasih.
