### ISSUE TITLE
Akses localhost error

### ISSUE THREAD

**Issue by jayaputra** [rsuregar/GundalaCMS#4]
![Screenshot at Mar 23 00-09-31](https://user-images.githubusercontent.com/33894932/77255531-ddca2f80-6c9a-11ea-9180-411030cd52d4.png)

Akses di localhost saya spt ini, mohon pencerahannya

Terimakasih.

**Comment by rsuregar** [comment]
Coba jalankan perintah php artisan config:cache atau ubah APP_DEBUG di .env menjadi true untuk melihat jebis error yang terjadi.

**Comment by jayaputra** [comment]
> Coba jalankan perintah php artisan config:cache atau ubah APP_DEBUG di .env menjadi true untuk melihat jenis error yang terjadi.

Sip, cms udh bisa diakses, makasih

**Comment by rsuregar** [comment]
semoga bermanfaat mas,. masih sangat sederhana hehehe. kalo ada masukan silakan ya mas. kita kembangkan sama-sama.
